language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t adityaacharya001/docker-react -f Dockerfile.dev .

script:
  - docker run adityaacharya001/docker-react npm run test -- --coverage  